language: php

php:
- 7.0
- 7.1
- 7.2
- hhvm

matrix:
  allow_failures:
  - php: hhvm

before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev
script:
- composer lint
- composer test
after_success:
- composer coveralls