services:
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy
    ports:
      - "8474:8474"

  ci-tests:
    build:
      context: .
      target: dev
    image: toxiproxy-php-client
    command: ["composer", "test"]
    environment:
      TOXIPROXY_HOST: toxiproxy
    depends_on:
      toxiproxy:
        condition: service_started
